# =====================================
# BUILD
# =====================================

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY . .

RUN dotnet restore

RUN dotnet publish Resguardo.Web/Shell.Web.csproj \
    -c Release \
    -o /app/publish

# =====================================
# RUNTIME
# =====================================

FROM tecsur/dotnet-runtime:8.0

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Resguardo.Web.dll"]